runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:BKtE4BIgQCEKTIWLIaP5HOnqsONA+64hXVFvC5um2dc=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_HOST: 127.0.0.1
  DB_DATABASE: courier
  DB_USERNAME: root
  DB_PASSWORD: password
  DB_SOCKET: "/cloudsql/littlepesa-c0420:asia-east1:courier"

beta_settings:
  cloud_sql_instances: "littlepesa-c0420:asia-east1:courier"
